version: '3.7'

services:
  php-fpm:
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
    build:
      context: docker/php-fpm
    links:
      - mysql

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - php-fpm

  mysql:
    build:
      context: docker/database
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    expose:
      - 3306
    ports:
      - 3308:3306
